    // Datos de los cantos
const songs = [

    {id:1,title: "A la víctima pascual", subtitle: "Secuencia de Pascua", category: "Precatecumenado", moments: ["Pascua", "Pentecostés", "Entrada", "Comunión", "Final", "Nuevo Testamento"], url: "/cantos/src/chtml/a/alavictimapascual.html"},
    {id:2,title: "A nadie demos ocasión de tropiezo", subtitle: "2ª Corintios 6,3ss", category: "Precatecumenado", moments: ["Nuevo Testamento"], url: "/cantos/src/chtml/a/anadiedemosocasiondetropiezo.html"},
    {id:3,title: "A ti levanto mis ojos", subtitle: "Salmo 123 (122)", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/src/chtml/a/atilevantomisojos.html"},
    {id:4,title: "A ti, Señor, en mi clamor imploro", subtitle: "Salmo 142 (141)", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/src/chtml/a/atisenorenmiclamorimploro.html"},
    {id:5,title: "A ti, Señor, levanto mi alma", subtitle: "Salmo 25 (24)", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/src/chtml/a/atisenorlevantomialma.html"},
    {id:6,title: "A ti, Señor, se debe la alabanza en Sión ", subtitle: "Salmo 65 (64)", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/a/atisenorsedebelaalabanzaension.html"},
    {id:7,title: "Abraham ", subtitle: "Teofanía de Mambré – Génesis 18,1-5", category: "Precatecumenado", moments: ["Laudes/Visperas", "Entrada", "Antiguo Testamento"], url: "/cantos/src/chtml/a/abraham.html"},
    {id:8,title: "Aclamad al Señor", subtitle: "Salmo 100 (99)", category: "Precatecumenado", moments: ["Laudes/Visperas", "Final", "Antiguo Testamento"], url: "/cantos/src/chtml/a/aclamadalsenor.html"},
    {id:9,title: "Al despertar", subtitle: "Salmo 17 (16)", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/a/aldespertar.html"},
    {id:10,title: "Alabad al Señor en el cielo", subtitle: "Salmo 148", category: "Precatecumenado", moments: ["Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/a/alabadalsenorenelcielo.html"},
    {id:11,title: "Alegría, ha nacido el salvador ", subtitle: "Villancico", category: "Precatecumenado", moments: ["Navidad", "Niños"], url: "/cantos/src/chtml/a/alegriahanacidoelsalvador.html"},
    {id:12,title: "Aleluya, alabad al Señor", subtitle: "Salmo 150", category: "Precatecumenado", moments: ["Pascua", "Laudes/Visperas", "Final", "Antiguo Testamento"], url: "/cantos/src/chtml/a/aleluyaalabadalsenor.html"},
    {id:13,title: "Aleluya, bendecid al Señor", subtitle: "Salmo 134 (133)", category: "Precatecumenado", moments: ["Pascua", "Niños", "Paz", "Antiguo Testamento"], url: "/cantos/src/chtml/a/aleluyabendecidalsenor.html"},
    {id:14,title: "Aleluya, ya llegó el reino", subtitle: "Apocalipsis 19,6-9", category: "Precatecumenado", moments: ["Laudes/Visperas", "Comunión", "Nuevo Testamento"], url: "/cantos/src/chtml/a/aleluyayallegoelreino.html"},
    {id:15,title: "Alzaos puertas ", subtitle: "Salmo 24 (23)", category: "Precatecumenado", moments: ["Entrada", "Antiguo Testamento"], url: "/cantos/src/chtml/a/alzaospuertas.html"},
    {id:16,title: "Amén, amén, amén", subtitle: "Apocalipsis 7,12-14", category: "Precatecumenado", moments: ["Entrada", "Nuevo Testamento"], url: "/cantos/src/chtml/a/amenamenamen.html"},
    {id:17,title: "Amo al Señor ", subtitle: "Salmo 116 (114-115)", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Antiguo Testamento", ""], url: "/cantos/src/chtml/a/amoalsenor.html"},
    {id:18,title: "Aquedah", subtitle: "Del Targum Neofiti sobre el sacrificio de Isaac (Gn 22,1-19)", category: "Precatecumenado", moments: ["Pascua", "Niños", "Fracción del Fracción del Pan", "Antiguo Testamento"], url: "/cantos/src/chtml/a/aquedah.html"},
    {id:19,title: "Ave María I ", subtitle: "Lucas 1,28ss", category: "Precatecumenado", moments: ["Virgen", "Nuevo Testamento"], url: "/cantos/src/chtml/a/avemariai.html"},
    {id:20,title: "Ave María II (1984)", subtitle: "Lucas 1,28ss", category: "Precatecumenado", moments: ["Virgen", "Final", "Nuevo Testamento"], url: "/cantos/src/chtml/a/avemariaii(1984).html"},
    {id:21,title: "Babilonia criminal ", subtitle: "Salmo 137 (136)", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/b/babiloniacriminal.html"},
    {id:22,title: "Balaam", subtitle: "Números 23,7-24", category: "Precatecumenado", moments: ["Paz", "Comunión", "Final", "Antiguo Testamento"], url: "/cantos/src/chtml/b/balaam.html"},
    {id:23,title: "Bendeciré al Señor en todo tiempo", subtitle: "Salmo 34 (33)", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/b/bendecirealsenorentodotiempo.html"},
    {id:24,title: "Bendice, alma mía, a Yahveh ", subtitle: "Salmo 103 (102)", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/b/bendicealmamiaayahveh.html"},
    {id:25,title: "Bendita eres tú, María", subtitle: "Lucas 1,42-45", category: "Precatecumenado", moments: ["Virgen", "Entrada", "Final", "Nuevo Testamento"], url: "/cantos/src/chtml/b/benditaerestumaria.html"},
    {id:26,title: "Bendito eres, Señor ", subtitle: "Daniel 3,52-57", category: "Precatecumenado", moments: ["Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/b/benditoeressenor.html"},
    {id:27,title: "Benedictus", subtitle: "Lucas 1,67-80", category: "Precatecumenado", moments: ["Laudes/Visperas", "Nuevo Testamento"], url: "/cantos/src/chtml/b/benedictus.html"},
    {id:28,title: "Cantad a Dios ", subtitle: "Salmo 67 (68) 2.4-7", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/c/cantadadios.html"},
    {id:29,title: "Cantad al Señor", subtitle: "Salmo 117 (116)", category: "Precatecumenado", moments: ["Laudes/Visperas", "Entrada", "Final", "Antiguo Testamento"], url: "/cantos/src/chtml/c/cantadalsenor.html"},
    {id:30,title: "Cántico de los tres jóvenes ", subtitle: "Daniel 3,57-58", category: "Precatecumenado", moments: ["Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/c/canticodelostresjovenes.html"},
    {id:31,title: "Canto de Moisés", subtitle: "Éxodo 15,1-18", category: "Precatecumenado", moments: ["Pascua", "Antiguo Testamento"], url: "/cantos/src/chtml/c/cantodemoises.html"},
    {id:32,title: "Caritas Christi urget nos ", subtitle: "2ª Corintios 5,14.15.17.21", category: "Precatecumenado", moments: ["Nuevo Testamento"], url: "/cantos/src/chtml/c/caritaschristiurgetnos.html"},
    {id:33,title: "Cómo es maravilloso", subtitle: "Salmo 133 (132)", category: "Precatecumenado", moments: ["Paz", "Antiguo Testamento"], url: "/cantos/src/chtml/c/comoesmaravilloso.html"},
    {id:34,title: "Como la cierva", subtitle: "Salmo 42-43 (41-42)", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/c/comolacierva.html"},
    {id:35,title: "Cristo es la luz", subtitle: "Himno", category: "Precatecumenado", moments: ["Entrada"], url: "/cantos/src/chtml/c/cristoeslaluz.html"},
    {id:36,title: "Cuando el Señor", subtitle: "Salmo 126 (125)", category: "Precatecumenado", moments: ["Cuaresma", "Entrada", "Final", "Antiguo Testamento"], url: "/cantos/src/chtml/c/cuandoelsenor.html"},
    {id:37,title: "Cuando Israel salió de Egipto ", subtitle: "Salmo 114 (113)", category: "Precatecumenado", moments: ["Pascua", "Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/c/cuandoisraelsaliodeegipto.html"},
    {id:38,title: "Dayenú ", subtitle: "De la Hagadá de Pésaj hebrea", category: "Precatecumenado", moments: ["Pascua", "Paz", "Final"], url: "/cantos/src/chtml/d/dayenu.html"},
    {id:39,title: "Dayenú ", subtitle: "", category: "Precatecumenado", moments: ["Pascua", "Paz"], url: "/cantos/src/chtml/d/dayenu.html"},
    {id:40,title: "De Profundis ", subtitle: "Salmo 130 (129)", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/src/chtml/d/deprofundis.html"},
    {id:41,title: "Decidle a los de corazón cansado ", subtitle: "Isaías 35,4ss", category: "Precatecumenado", moments: ["Cuaresma", "Entrada", "Antiguo Testamento"], url: "/cantos/src/chtml/d/decidlealosdecorazoncansado.html"},
    {id:42,title: "Delante de los ángeles ", subtitle: "Salmo 138 (137)", category: "Precatecumenado", moments: ["Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/d/delantedelosangeles.html"},
    {id:43,title: "Día de reposo ", subtitle: "Juan 8,52", category: "Precatecumenado", moments: ["Final", "Nuevo Testamento"], url: "/cantos/src/chtml/d/diadereposo.html"},
    {id:44,title: "Dice el Señor a mi Señor", subtitle: "Salmo 110 (109)", category: "Precatecumenado", moments: ["Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/d/diceelsenoramisenor.html"},
    {id:45,title: "Dichoso el hombre ", subtitle: "Salmo 1", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/d/dichosoelhombre.html"},
    {id:46,title: "El necio piensa que Dios no existe", subtitle: "Salmo 14 (13)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/e/elneciopiensaquediosnoexiste.html"},
    {id:47,title: "El pueblo que caminaba en las tinieblas ", subtitle: "Isaías 9,1-5", category: "Precatecumenado", moments: ["Navidad", "Antiguo Testamento"], url: "/cantos/src/chtml/e/elpuebloquecaminabaenlastinieblas.html"},
    {id:48,title: "El Señor anuncia una noticia", subtitle: "Salmo 68 (67)", category: "Precatecumenado", moments: ["Adviento", "Entrada", "Antiguo Testamento"], url: "/cantos/src/chtml/e/elsenoranunciaunanoticia.html"},
    {id:49,title: "El Señor es mi pastor", subtitle: "Salmo 23 (22)", category: "Precatecumenado", moments: ["Comunión", "Antiguo Testamento"], url: "/cantos/src/chtml/e/elsenoresmipastor.html"},
    {id:50,title: "Elí, Elí, lamá sabactaní ", subtitle: "Salmo 22 (21)", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/src/chtml/e/elielilamasabactani.html"},
    {id:51,title: "En medio de aquel gentío ", subtitle: "Lucas 8,42b-48", category: "Precatecumenado", moments: ["Entrada", "Comunión", "Nuevo Testamento"], url: "/cantos/src/chtml/e/enmediodeaquelgentio.html"},
    {id:52,title: "Eres hermoso", subtitle: "Salmo 45 (44)", category: "Precatecumenado", moments: ["Entrada", "Final", "Antiguo Testamento"], url: "/cantos/src/chtml/e/ereshermoso.html"},
    {id:53,title: "Escóndeme en lo oculto de tu tienda ", subtitle: "Salmo 27 (26)", category: "Precatecumenado", moments: ["Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/e/escondemeenloocultodetutienda.html"},
    {id:54,title: "Están rotas mis ataduras ", subtitle: "Carmen 63 – Poema de Rabindranath Tagore", category: "Precatecumenado", moments: [""], url: "/cantos/src/chtml/e/estanrotasmisataduras.html"},
    {id:55,title: "Éste es el día en que actuó el Señor", subtitle: "Salmo 118 (117)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/é/esteeseldiaenqueactuoelsenor.html"},
    {id:56,title: "Este es mandamiento mío", subtitle: "Juan 15,12ss", category: "Precatecumenado", moments: ["Pascua", "Fracción del Fracción del Pan", "Comunión", "Nuevo Testamento"], url: "/cantos/src/chtml/e/esteesmandamientomio.html"},
    {id:57,title: "Evenu shalom alejem ", subtitle: "Canto popular Hebreo", category: "Precatecumenado", moments: ["Paz"], url: "/cantos/src/chtml/e/evenushalomalejem.html"},
    {id:58,title: "Exultad, justos, en el Señor", subtitle: "Salmo 33 (32)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/e/exultadjustosenelsenor.html"},
    {id:59,title: "Felicidad para el hombre ", subtitle: "Salmo 128 (127)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/f/felicidadparaelhombre.html"},
    {id:60,title: "Gracias a Yahveh ", subtitle: "Salmo 136 (135)", category: "Precatecumenado", moments: ["Paz", "Comunión", "Final", "Antiguo Testamento"], url: "/cantos/src/chtml/g/graciasayahveh.html"},
    {id:61,title: "Gritad jubilosos ", subtitle: "Isaías 12", category: "Precatecumenado", moments: ["Entrada", "Antiguo Testamento"], url: "/cantos/src/chtml/g/gritadjubilosos.html"},
    {id:62,title: "Hacia ti morada santa ", subtitle: "Himno", category: "Precatecumenado", moments: ["Entrada"], url: "/cantos/src/chtml/h/haciatimoradasanta.html"},
    {id:63,title: "Hasta cuándo ", subtitle: "Salmo 13 (12)", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/src/chtml/h/hastacuando.html"},
    {id:64,title: "He aquí que vengo presto ", subtitle: "Apocalipsis 22,12-16", category: "Precatecumenado", moments: ["Adviento", "Nuevo Testamento"], url: "/cantos/src/chtml/h/heaquiquevengopresto.html"},
    {id:65,title: "He esperado en el Señor", subtitle: "Salmo 40 (39)", category: "Precatecumenado", moments: ["Adviento", "Cuaresma", "Antiguo Testamento"], url: "/cantos/src/chtml/h/heesperadoenelsenor.html"},
    {id:66,title: "Hijas de Jerusalén", subtitle: "Lucas 23,28-46", category: "Precatecumenado", moments: ["Cuaresma", "Nuevo Testamento"], url: "/cantos/src/chtml/h/hijasdejerusalen.html"},
    {id:67,title: "Himno a Cristo Luz ", subtitle: "Himno", category: "Precatecumenado", moments: ["Pascua"], url: "/cantos/src/chtml/h/himnoacristoluz.html"},
    {id:68,title: "Himno a la kenosis", subtitle: "Filipenses 2,1-11", category: "Precatecumenado", moments: ["Cuaresma", "Fracción del Fracción del Pan", "Nuevo Testamento"], url: "/cantos/src/chtml/h/himnoalakenosis.html"},
    {id:69,title: "Himno de Adviento", subtitle: "Himno", category: "Precatecumenado", moments: ["Adviento"], url: "/cantos/src/chtml/h/himnodeadviento.html"},
    {id:70,title: "Himno de la Ascensión", subtitle: "Himno de Laudes del tiempo Pascual, de la Ascensión a Pentecostés", category: "Precatecumenado", moments: ["Laudes/Visperas"], url: "/cantos/src/chtml/h/himnodelaascension.html"},
    {id:71,title: "Himno de Pascua ", subtitle: "Himno", category: "Precatecumenado", moments: ["Pascua", "Laudes/Visperas"], url: "/cantos/src/chtml/h/himnodepascua.html"},
    {id:72,title: "Id y anunciad a mis hermanos", subtitle: "Mateo 28,7-10.16-20", category: "Precatecumenado", moments: ["Final", "Nuevo Testamento"], url: "/cantos/src/chtml/i/idyanunciadamishermanos.html"},
    {id:73,title: "Improperios", subtitle: "De la Liturgia de la Adoración de la Cruz de Viernes Santo", category: "Precatecumenado", moments: ["Cuaresma"], url: "/cantos/src/chtml/i/improperios.html"},
    {id:74,title: "Jerusalén reconstruida ", subtitle: "Tobías 13,11-17", category: "Precatecumenado", moments: ["Cuaresma", "Paz", "Antiguo Testamento"], url: "/cantos/src/chtml/j/jerusalenreconstruida.html"},
    {id:75,title: "La marcha es dura ", subtitle: "Himno*", category: "Precatecumenado", moments: ["Cuaresma"], url: "/cantos/src/chtml/l/lamarchaesdura.html"},
    {id:76,title: "La Salve ", subtitle: "Himno", category: "Precatecumenado", moments: ["Virgen"], url: "/cantos/src/chtml/l/lasalve.html"},
    {id:77,title: "La siega de las naciones ", subtitle: "Juan 4,31-38", category: "Precatecumenado", moments: ["Final", "Nuevo Testamento"], url: "/cantos/src/chtml/l/lasiegadelasnaciones.html"},
    {id:78,title: "Levanto mis ojos a los montes ", subtitle: "Salmo 121 (120)", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Entrada", "Antiguo Testamento"], url: "/cantos/src/chtml/l/levantomisojosalosmontes.html"},
    {id:79,title: "Llegue hasta tu presencia mi clamor ", subtitle: "Salmo 119 (118)", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Entrada"], url: "/cantos/src/chtml/l/lleguehastatupresenciamiclamor.html"},
    {id:80,title: "Llévame al cielo ", subtitle: "Filipenses 1,23", category: "Precatecumenado", moments: ["Adviento", "Pentecostés", "Final", "Nuevo Testamento"], url: "/cantos/src/chtml/l/llevamealcielo.html"},
    {id:81,title: "Magníficat", subtitle: "Lucas 1,46-55", category: "Precatecumenado", moments: ["Virgen", "Laudes/Visperas", "Nuevo Testamento"], url: "/cantos/src/chtml/m/magnificat.html"},
    {id:82,title: "María, casa de bendición", subtitle: "Las Bodas de Caná – Juan 2,1-11", category: "Precatecumenado", moments: ["Virgen", "Entrada", "Nuevo Testamento"], url: "/cantos/src/chtml/m/mariacasadebendicion.html"},
    {id:83,title: "María de Jasna Göra", subtitle: "Himno a la Virgen de Jasna Göra, Chestokowa, Polonia", category: "Precatecumenado", moments: ["Virgen"], url: "/cantos/src/chtml/m/mariadejasnagöra.html"},
    {id:84,title: "María, madre de la Iglesia", subtitle: "Juan 19,26-34", category: "Precatecumenado", moments: ["Cuaresma", "Virgen", "Nuevo Testamento"], url: "/cantos/src/chtml/m/mariamadredelaiglesia.html"},
    {id:85,title: "María, madre del camino ardiente", subtitle: "Himno a la Virgen del Tercer Milenio", category: "Precatecumenado", moments: ["Virgen"], url: "/cantos/src/chtml/m/mariamadredelcaminoardiente.html"},
    {id:86,title: "María, pequeña María", subtitle: "Himno", category: "Precatecumenado", moments: ["Cuaresma", "Virgen"], url: "/cantos/src/chtml/m/mariapequenamaria.html"},
    {id:87,title: "Me enseñarás el camino de la vida", subtitle: "Salmo 16 (15)", category: "Precatecumenado", moments: ["Adviento", "Entrada", "Antiguo Testamento"], url: "/cantos/src/chtml/m/meensenaraselcaminodelavida.html"},
    {id:88,title: "Me has seducido, Señor", subtitle: "Jeremías 20,7-18", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/m/mehasseducidosenor.html"},
    {id:89,title: "Mirad qué estupendo ", subtitle: "Salmo 133 (132)", category: "Precatecumenado", moments: ["Paz", "Antiguo Testamento"], url: "/cantos/src/chtml/m/miradqueestupendo.html"},
    {id:90,title: "Misericordia mía, misericordia", subtitle: "Salmo 51 (50) “Miserere”", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/m/misericordiamiamisericordia.html"},
    {id:91,title: "Mucho me han perseguido", subtitle: "Salmo 129 (128)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/m/muchomehanperseguido.html"},
    {id:92,title: "No está aquí, resucitó ", subtitle: "Mateo 28,1-8", category: "Precatecumenado", moments: ["Pascua", "Comunión", "Nuevo Testamento"], url: "/cantos/src/chtml/n/noestaaquiresucito.html"},
    {id:93,title: "Oh cielos, lloved de lo alto", subtitle: "Isaías 45,8", category: "Precatecumenado", moments: ["Adviento"], url: "/cantos/src/chtml/o/ohcieloslloveddeloalto.html"},
    {id:94,title: "Oh Dios, por tu nombre sálvame ", subtitle: "Salmo 54 (53)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/o/ohdiosportunombresalvame.html"},
    {id:95,title: "Oh Dios, tú eres mi Dios ", subtitle: "Salmo 63 (62)", category: "Precatecumenado", moments: ["Adviento", "Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/o/ohdiostueresmidios.html"},
    {id:96,title: "Oh Jesús, amor mío ", subtitle: "Himno", category: "Precatecumenado", moments: ["Cuaresma", "Fracción del Pan", "Comunión"], url: "/cantos/src/chtml/o/ohjesusamormio.html"},
    {id:97,title: "Oh muerte, ¿dónde está tu victoria? ", subtitle: "1ª Corintios 15", category: "Precatecumenado", moments: ["Pascua", "Nuevo Testamento"], url: "/cantos/src/chtml/o/ohmuerte¿dondeestatuvictoria?.html"},
    {id:98,title: "Oh Señor, nuestro Dios ", subtitle: "Salmo 8", category: "Precatecumenado", moments: ["Laudes/Visperas", "Entrada", "Comunión", "Antiguo Testamento"], url: "/cantos/src/chtml/o/ohsenornuestrodios.html"},
    {id:99,title: "Os tomaré de entre las naciones ", subtitle: "Cántico de Ezequiel – Ez 36,24-28", category: "Precatecumenado", moments: ["Entrada", "Antiguo Testamento"], url: "/cantos/src/chtml/o/ostomaredeentrelasnaciones.html"},
    {id:100,title: "Paloma incorrupta ", subtitle: "Himno inspirado en los Kontákia de san Romano el Meloda", category: "Precatecumenado", moments: ["Virgen"], url: "/cantos/src/chtml/p/palomaincorrupta.html"},
    {id:101,title: "Pentecostés", subtitle: "Himno", category: "Precatecumenado", moments: ["Pentecostés", "Comunión"], url: "/cantos/src/chtml/p/pentecostes.html"},
    {id:102,title: "Por el amor de mis amigos ", subtitle: "Salmo 122 (121)", category: "Precatecumenado", moments: ["Paz", "Antiguo Testamento"], url: "/cantos/src/chtml/p/porelamordemisamigos.html"},
    {id:103,title: "Por qué esta noche es diferente ", subtitle: "Canto de los niños para la Noche de Pascua – de la Hagadá de Pésaj hebrea", category: "Precatecumenado", moments: ["Pascua", "Niños", "Paz"], url: "/cantos/src/chtml/p/porqueestanocheesdiferente.html"},
    {id:104,title: "Por qué las gentes conjuran ", subtitle: "Salmo 2", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/p/porquelasgentesconjuran.html"},
    {id:105,title: "Porque mi yugo es suave ", subtitle: "Mateo 11,28-30", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Nuevo Testamento"], url: "/cantos/src/chtml/p/porquemiyugoessuave.html"},
    {id:106,title: "Qué amables son tus moradas ", subtitle: "Salmo 84 (83)", category: "Precatecumenado", moments: ["Entrada", "Antiguo Testamento"], url: "/cantos/src/chtml/q/queamablessontusmoradas.html"},
    {id:107,title: "Qué estupendo, qué alegría", subtitle: "Salmo 133 (132)", category: "Precatecumenado", moments: ["Paz", "Antiguo Testamento"], url: "/cantos/src/chtml/q/queestupendoquealegria.html"},
    {id:108,title: "Quién nos separará", subtitle: "Romanos 8,34-39", category: "Precatecumenado", moments: ["Laudes/Visperas", "Comunión", "Nuevo Testamento"], url: "/cantos/src/chtml/q/quiennosseparara.html"},
    {id:109,title: "Quiero cantar ", subtitle: "Salmo 57 (56)", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/src/chtml/q/quierocantar.html"},
    {id:110,title: "Resucitó ", subtitle: "1 Corintios 15", category: "Precatecumenado", moments: ["Pascua", "Comunión"], url: "/cantos/src/chtml/r/resucito.html"},
    {id:111,title: "Resurrexit ", subtitle: "Diálogo de Nuestro Señor Jesucristo con Marta - Jn 11,25-27", category: "Precatecumenado", moments: ["Pascua"], url: "/cantos/src/chtml/r/resurrexit.html"},
    {id:112,title: "Salve, reina de los cielos ", subtitle: "Himno", category: "Precatecumenado", moments: ["Virgen", "Final"], url: "/cantos/src/chtml/s/salvereinadeloscielos.html"},
    {id:113,title: "Se encontraron dos ángeles ", subtitle: "Canto de los niños", category: "Precatecumenado", moments: ["Niños", "Paz"], url: "/cantos/src/chtml/s/seencontrarondosangeles.html"},
    {id:114,title: "Secuencia del Corpus Christi ", subtitle: "Solemnidad del Cuerpo y la Sangre de Cristo", category: "Precatecumenado", moments: ["Pentecostés", "Entrada"], url: "/cantos/src/chtml/s/secuenciadelcorpuschristi.html"},
    {id:115,title: "Secuencia del Corpus Christi ", subtitle: "Solemnidad del Cuerpo y la Sangre de Cristo", category: "Precatecumenado", moments: [""], url: "/cantos/src/chtml/s/secuenciadelcorpuschristi.html"},
    {id:116,title: "Señor, ayúdame a no dudar de ti", subtitle: "Kiko Argüello", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Comunión"], url: "/cantos/src/chtml/s/senorayudameanodudardeti.html"},
    {id:117,title: "Señor, no me corrijas en tu cólera", subtitle: "Salmo 6", category: "Precatecumenado", moments: ["Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/s/senornomecorrijasentucolera.html"},
    {id:118,title: "Shlom-lej Mariam", subtitle: "Ave María en arameo antiguo", category: "Precatecumenado", moments: ["Virgen", "Final"], url: "/cantos/src/chtml/s/shlom-lejmariam.html"},
    {id:119,title: "Si el Señor no construye la casa ", subtitle: "Salmo 127 (126)", category: "Precatecumenado", moments: ["Entrada", "Antiguo Testamento"], url: "/cantos/src/chtml/s/sielsenornoconstruyelacasa.html"},
    {id:120,title: "Si habéis resucitado con Cristo ", subtitle: "Colosenses 3,1-4", category: "Precatecumenado", moments: ["Adviento", "Pascua"], url: "/cantos/src/chtml/s/sihabeisresucitadoconcristo.html"},
    {id:121,title: "Si hoy escucháis su voz", subtitle: "Salmo 95 (94)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/s/sihoyescuchaissuvoz.html"},
    {id:122,title: "Si me he refugiado en el Señor", subtitle: "Salmo 11 (10)", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/src/chtml/s/simeherefugiadoenelsenor.html"},
    {id:123,title: "Sión, madre de todos los pueblos ", subtitle: "Salmo 87 (86)", category: "Precatecumenado", moments: ["Final", "Antiguo Testamento"], url: "/cantos/src/chtml/s/sionmadredetodoslospueblos.html"},
    {id:124,title: "Sola a Solo ", subtitle: "Himno", category: "Precatecumenado", moments: ["Virgen"], url: "/cantos/src/chtml/s/solaasolo.html"},
    {id:125,title: "Stabat mater dolorosa", subtitle: "Secuencia del siglo XIII", category: "Precatecumenado", moments: ["Cuaresma", "Virgen"], url: "/cantos/src/chtml/s/stabatmaterdolorosa.html"},
    {id:126,title: "Sube Dios entre aclamaciones ", subtitle: "Salmo 47 (46)", category: "Precatecumenado", moments: ["Pascua", "Pentecostés", "Paz"], url: "/cantos/src/chtml/s/subediosentreaclamaciones.html"},
    {id:127,title: "Te estoy llamando, Señor", subtitle: "Salmo 141 (140)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/t/teestoyllamandosenor.html"},
    {id:128,title: "Te he manifestado mi pecado ", subtitle: "Salmo 32 (31)", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/src/chtml/t/tehemanifestadomipecado.html"},
    {id:129,title: "Tú que eres fiel", subtitle: "Salmo 143 (142)", category: "Precatecumenado", moments: ["Cuaresma", "Entrada", "Antiguo Testamento"], url: "/cantos/src/chtml/t/tuqueeresfiel.html"},
    {id:130,title: "Un retoño brota del tronco de Jesé ", subtitle: "Isaías 11,1-11", category: "Precatecumenado", moments: ["Navidad", "Pentecostés", "Comunión", "Antiguo Testamento"], url: "/cantos/src/chtml/u/unretonobrotadeltroncodejese.html"},
    {id:131,title: "Una gran señal ", subtitle: "Apocalipsis 12", category: "Precatecumenado", moments: ["Adviento", "Pentecostés", "Virgen", "Nuevo Testamento"], url: "/cantos/src/chtml/u/unagransenal.html"},
    {id:132,title: "Urí, urí, urí, urá", subtitle: "Villancico", category: "Precatecumenado", moments: ["Navidad", "Niños"], url: "/cantos/src/chtml/u/uriuriuriura.html"},
    {id:133,title: "Vamos ya, pastores ", subtitle: "Villancico", category: "Precatecumenado", moments: ["Navidad", "Niños"], url: "/cantos/src/chtml/v/vamosyapastores.html"},
    {id:134,title: "Ven, Espíritu Santo ", subtitle: "Secuencia de Pentecostés", category: "Precatecumenado", moments: ["Pentecostés"], url: "/cantos/src/chtml/v/venespiritusanto.html"},
    {id:135,title: "Ven, Hijo del Hombre ", subtitle: "Apocalipsis 21, 17ss", category: "Precatecumenado", moments: ["Adviento", "Final", "Nuevo Testamento"], url: "/cantos/src/chtml/v/venhijodelhombre.html"},
    {id:136,title: "Veni Creator ", subtitle: "Himno de vísperas de Pascua, de la Ascensión a Pentecostés", category: "Precatecumenado", moments: ["Pentecostés"], url: "/cantos/src/chtml/v/venicreator.html"},
    {id:137,title: "Viene el Señor  - Salmo 93 (92) – Apocalipsis 1,5-6", subtitle: "Salmo 93 (92) – Apocalipsis 1,5-6", category: "Precatecumenado", moments: ["Adviento", "Pentecostés", "Antiguo Testamento", "Nuevo Testamento"], url: "/cantos/src/chtml/v/vieneelsenor-salmo93(92)–apocalipsis15-6.html"},
    {id:138,title: "Virgen de la maravilla ", subtitle: "Himno *", category: "Precatecumenado", moments: ["Virgen"], url: "/cantos/src/chtml/v/virgendelamaravilla.html"},
    {id:139,title: "Vivid alegres", subtitle: "Filipenses 4,4ss", category: "Precatecumenado", moments: ["Adviento", "Niños", "Nuevo Testamento"], url: "/cantos/src/chtml/v/vividalegres.html"},
    {id:140,title: "Vosotros sois la luz del mundo", subtitle: "Mateo 5,14-16", category: "Precatecumenado", moments: ["Nuevo Testamento"], url: "/cantos/src/chtml/v/vosotrossoislaluzdelmundo.html"},
    {id:141,title: "Ya viene mi Dios ", subtitle: "Villancico", category: "Precatecumenado", moments: ["Navidad", "Niños"], url: "/cantos/src/chtml/y/yavienemidios.html"},
    {id:142,title: "Yahveh, tú eres mi Dios", subtitle: "Isaías 25", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/src/chtml/y/yahvehtueresmidios.html"},
    {id:143,title: "Yo te amo, Señor ", subtitle: "Salmo 18 (17)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/y/yoteamosenor.html"},
    {id:144,title: "Yo vengo a reunir", subtitle: "Isaías 66,18-21", category: "Precatecumenado", moments: ["Entrada", "Final", "Antiguo Testamento"], url: "/cantos/src/chtml/y/yovengoareunir.html"},
    {id:145,title: "Zaqueo", subtitle: "Lucas 19,1-10", category: "Precatecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Entrada", "Comunión", "Nuevo Testamento"], url: "/cantos/src/chtml/z/zaqueo.html"},
    {id:147,title: "Aleluya interleccional", subtitle: "Apropiados para los tiempos de Adviento, Navidad y Ordinario", category: "Liturgia", moments: ["Adviento", "Navidad", "Ordinario"], url: "/cantos/src/chtml/a/aleluyainterleccional.html"},
    {id:148,title: "Aleluya pascual ", subtitle: "Apropiado para el tiempo Pascual *", category: "Liturgia", moments: ["Pascua"], url: "/cantos/src/chtml/a/aleluyapascual.html"},
    {id:149,title: "Antífona – versículo antes del Evangelio ", subtitle: "Apropiado para el tiempo de Cuaresma", category: "Liturgia", moments: ["Cuaresma"], url: "/cantos/src/chtml/a/antifona–versiculoantesdelevangelio.html"},
    {id:150,title: "Bendición del agua", subtitle: "De Liturgia Bautismal de la Vigilia Pascual", category: "Liturgia", moments: ["Pascua"], url: "/cantos/src/chtml/b/bendiciondelagua.html"},
    {id:151,title: "Bendición del agua", subtitle: "", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/b/bendiciondelagua.html"},
    {id:152,title: "Bendición penitencial ", subtitle: "Oración conclusiva de acción de gracias para la Celebración Penitencial", category: "Liturgia", moments: ["Penitencial"], url: "/cantos/src/chtml/b/bendicionpenitencial.html"},
    {id:153,title: "Cordero de Dios", subtitle: "Letanía del Cordero de Dios", category: "Liturgia", moments: ["Fracción del Pan"], url: "/cantos/src/chtml/c/corderodedios.html"},
    {id:154,title: "Credo", subtitle: "Símbolo Apostólico", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/c/credo.html"},
    {id:155,title: "Gloria a Dios en lo alto del cielo ", subtitle: "Himno Litúrgico", category: "Liturgia", moments: ["Pascua"], url: "/cantos/src/chtml/g/gloriaadiosenloaltodelcielo.html"},
    {id:156,title: "Letanías de los santos", subtitle: "De Liturgia Bautismal de la Vigilia Pascual", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/l/letaniasdelossantos.html"},
    {id:157,title: "Letanías de los santos", subtitle: "", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/l/letaniasdelossantos.html"},
    {id:158,title: "Letanías penitenciales I ", subtitle: "Letanía para la Celebración Penitencial – modelo abreviado", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/l/letaniaspenitencialesi.html"},
    {id:159,title: "Letanías penitenciales II", subtitle: "Letanía para la Celebración Penitencial", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/l/letaniaspenitencialesii.html"},
    {id:160,title: "Letanías penitenciales II", subtitle: "", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/l/letaniaspenitencialesii.html"},
    {id:161,title: "Padre nuestro", subtitle: "Tiempo de la Elección", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/padrenuestro.html"},
    {id:162,title: "Plegaria Eucarística II – Modelo I ", subtitle: "Modelo I ", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/plegariaeucaristicaii–modeloi.html"},
    {id:163,title: "Plegaria Eucarística II – Modelo I ", subtitle: "Modelo I ", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/plegariaeucaristicaii–modeloi.html"},
    {id:164,title: "Plegaria Eucarística II – Modelo I ", subtitle: "Modelo I ", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/plegariaeucaristicaii–modeloi.html"},
    {id:165,title: "Plegaria Eucarística II – Modelo II (1987)", subtitle: "Modelo II (1987) ", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/plegariaeucaristicaii–modeloii(1987).html"},
    {id:166,title: "Plegaria Eucarística II – Modelo II (1987)", subtitle: "Modelo II (1987) ", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/plegariaeucaristicaii–modeloii(1987).html"},
    {id:167,title: "Plegaria Eucarística II – Modelo II (1987)", subtitle: "Modelo II (1987) ", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/plegariaeucaristicaii–modeloii(1987).html"},
    {id:168,title: "Plegaria Eucarística IV – (1988)", subtitle: "(1988)", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/plegariaeucaristicaiv–(1988).html"},
    {id:169,title: "Plegaria Eucarística IV – (1988)", subtitle: "(1988)", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/plegariaeucaristicaiv–(1988).html"},
    {id:170,title: "Plegaria Eucarística IV – (1988)", subtitle: "(1988)", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/plegariaeucaristicaiv–(1988).html"},
    {id:171,title: "Plegaria Eucarística IV – (1988)", subtitle: "(1988)", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/p/plegariaeucaristicaiv–(1988).html"},
    {id:172,title: "Prefacio para Adviento y Navidad ", subtitle: "Prefacio de Adviento II – Melodía para el tiempo de Adviento y Navidad", category: "Liturgia", moments: ["Adviento", "Navidad"], url: "/cantos/src/chtml/p/prefacioparaadvientoynavidad.html"},
    {id:173,title: "Prefacio para el tiempo Pascual", subtitle: "Prefacio de Pascua I – Melodía para el tiempo Pascual", category: "Liturgia", moments: ["Pascua"], url: "/cantos/src/chtml/p/prefacioparaeltiempopascual.html"},
    {id:174,title: "Pregón Pascual", subtitle: "Pregón solemne de la Vigilia Pascual", category: "Liturgia", moments: ["Pascua"], url: "/cantos/src/chtml/p/pregonpascual.html"},
    {id:175,title: "Pregón Pascual", subtitle: "Pregón solemne de la Vigilia Pascual", category: "Liturgia", moments: ["Pascua"], url: "/cantos/src/chtml/p/pregonpascual.html"},
    {id:176,title: "Salmodia para el Salmo responsorial", subtitle: "XXII Domingo del Tiempo ordinario – Año A", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/salmodiaparaelsalmoresponsorial.html"},
    {id:177,title: "Salmodia para las Oraciones universales ", subtitle: "Melodía para utilizar en las Oraciones universales", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/salmodiaparalasoracionesuniversales.html"},
    {id:178,title: "Santo Palomeras 65 ", subtitle: "Tiempo de Adviento – Navidad", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/santopalomeras65.html"},
    {id:179,title: "Santo Hebreo ", subtitle: "Tiempo de Cuaresma", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/santohebreo.html"},
    {id:180,title: "Santo Palestina 74 ", subtitle: "Tiempo Pascual", category: "Liturgia", moments: [""], url: "/cantos/src/chtml/s/santopalestina74.html"},
    {id:181,title: "Santo Roma 77 ", subtitle: "Tiempo Ordinario", category: "Liturgia", moments: ["Ordinario"], url: "/cantos/src/chtml/s/santoroma77.html"},
    {id:182,title: "Santo 1982 ", subtitle: "Tiempo Ordinario", category: "Liturgia", moments: ["Ordinario"], url: "/cantos/src/chtml/s/santo1982.html"},
    {id:183,title: "Santo 1988 ", subtitle: "Tiempo Ordinario", category: "Liturgia", moments: ["Ordinario"], url: "/cantos/src/chtml/s/santo1988.html"},
    {id:184,title: "Te Deum", subtitle: "Himno", category: "Liturgia", moments: ["Laudes/Visperas"], url: "/cantos/src/chtml/t/tedeum.html"},
    {id:185,title: "Así habla el amén ", subtitle: "Apocalipsis 3,14-22", category: "Catecumenado", moments: ["Cuaresma"], url: "/cantos/src/chtml/a/asihablaelamen.html"},
    {id:186,title: "Bendito sea Dios ", subtitle: "Efesios 1,3-13", category: "Catecumenado", moments: [""], url: "/cantos/src/chtml/b/benditoseadios.html"},
    {id:187,title: "Como el impulso que siente la ira ", subtitle: "Oda VII de Salomón", category: "Catecumenado", moments: ["Laudes/Visperas", "Entrada", "Comunión"], url: "/cantos/src/chtml/c/comoelimpulsoquesientelaira.html"},
    {id:188,title: "Consolad a mi pueblo ", subtitle: "Isaías 40,1-11", category: "Catecumenado", moments: ["Adviento", "Entrada", "Paz", "Final", "Antiguo Testamento"], url: "/cantos/src/chtml/c/consoladamipueblo.html"},
    {id:189,title: "Débora", subtitle: "Jueces 5", category: "Catecumenado", moments: ["Adviento", "Virgen", "Antiguo Testamento"], url: "/cantos/src/chtml/d/debora.html"},
    {id:190,title: "El combate escatológico", subtitle: "Apocalipsis 19,11-20", category: "Catecumenado", moments: ["Pascua", "Entrada", "Nuevo Testamento"], url: "/cantos/src/chtml/e/elcombateescatologico.html"},
    {id:191,title: "El lagarero ", subtitle: "Isaías 63,1-6", category: "Catecumenado", moments: ["Fracción del Pan", "Antiguo Testamento"], url: "/cantos/src/chtml/e/ellagarero.html"},
    {id:192,title: "El mismo Dios", subtitle: "2ª Corintios 4,6-12", category: "Catecumenado", moments: ["Comunión", "Nuevo Testamento"], url: "/cantos/src/chtml/e/elmismodios.html"},
    {id:193,title: "El sembrador", subtitle: "Marcos 4,3ss", category: "Catecumenado", moments: ["Entrada", "Nuevo Testamento"], url: "/cantos/src/chtml/e/elsembrador.html"},
    {id:194,title: "El Señor me ha dado ", subtitle: "Tercer canto del Siervo de Yahveh – Isaías 50,4-10", category: "Catecumenado", moments: ["Fracción del Pan", "Antiguo Testamento"], url: "/cantos/src/chtml/e/elsenormehadado.html"},
    {id:195,title: "Eres digno de tomar el libro", subtitle: "Apocalipsis 5,9ss", category: "Catecumenado", moments: ["Laudes/Visperas", "Fracción del Pan", "Nuevo Testamento"], url: "/cantos/src/chtml/e/eresdignodetomarellibro.html"},
    {id:196,title: "Escuchad islas lejanas ", subtitle: "Segundo canto del Siervo de Yahveh – Isaías 49,1-16", category: "Catecumenado", moments: ["Entrada", "Fracción del Pan", "Antiguo Testamento"], url: "/cantos/src/chtml/e/escuchadislaslejanas.html"},
    {id:197,title: "He aquí mi siervo ", subtitle: "Primer canto del Siervo de Yahveh – Isaías 42", category: "Catecumenado", moments: ["Fracción del Pan", "Antiguo Testamento"], url: "/cantos/src/chtml/h/heaquimisiervo.html"},
    {id:198,title: "He aquí que nuestro espejo es el Señor", subtitle: "Oda XIII de Salomó", category: "Catecumenado", moments: ["Cuaresma", "Pascua", "Laudes/Visperas"], url: "/cantos/src/chtml/h/heaquiquenuestroespejoeselsenor.html"},
    {id:199,title: "Himno a la cruz gloriosa ", subtitle: "De la homilía “La Santa Pascua” de un autor anónimo del siglo II", category: "Catecumenado", moments: ["Laudes/Visperas", "Entrada"], url: "/cantos/src/chtml/h/himnoalacruzgloriosa.html"},
    {id:200,title: "Jacob ", subtitle: "Génesis 32,23-29", category: "Catecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/j/jacob.html"},
    {id:201,title: "Las armas de la luz", subtitle: "Efesios 6,11ss", category: "Catecumenado", moments: ["Cuaresma", "Laudes/Visperas", "Nuevo Testamento"], url: "/cantos/src/chtml/l/lasarmasdelaluz.html"},
    {id:202,title: "Ninguno puede servir a dos señores ", subtitle: "Mateo 6,24-33", category: "Catecumenado", moments: ["Nuevo Testamento"], url: "/cantos/src/chtml/n/ningunopuedeserviradossenores.html"},
    {id:203,title: "No hay en él parecer", subtitle: "Cuarto canto del Siervo de Yahveh - Isaías 53,2ss", category: "Catecumenado", moments: ["Fracción del Pan", "Antiguo Testamento"], url: "/cantos/src/chtml/n/nohayenelparecer.html"},
    {id:204,title: "No sufras por los malvados", subtitle: "Salmo 37 (36)", category: "Catecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/src/chtml/n/nosufrasporlosmalvados.html"},
    {id:205,title: "Oh Señor, mi corazón ya no es ambicioso ", subtitle: "Salmo 131 (130)", category: "Catecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/o/ohsenormicorazonyanoesambicioso.html"},
    {id:206,title: "Señor, tú me escrutas y conoces ", subtitle: "Salmo 139 (138)", category: "Catecumenado", moments: ["Antiguo Testamento"], url: "/cantos/src/chtml/s/senortumeescrutasyconoces.html"},
    {id:207,title: "Shemá Israel", subtitle: "Deuteronomio 6,4-9", category: "Catecumenado", moments: ["Pentecostés", "Antiguo Testamento"], url: "/cantos/src/chtml/s/shemaisrael.html"},
    {id:208,title: "Siéntate solitario y silencioso ", subtitle: "Lamentaciones 3", category: "Catecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/src/chtml/s/sientatesolitarioysilencioso.html"},
    {id:209,title: "Tú has cubierto de vergüenza la muerte ", subtitle: "Homilía de Melitón de Sardes sobre la Pascua – Oficio de Lecturas de Jueves Santo", category: "Catecumenado", moments: ["Pascua", "Virgen", "Fracción del Pan"], url: "/cantos/src/chtml/t/tuhascubiertodevergüenzalamuerte.html"},
    {id:211,title: "A la cena del cordero", subtitle: "Himno de Vísperas del tiempo Pascual hasta la Ascensión", category: "Eleccion", moments: ["Pascua", "Laudes/Visperas", "Entrada"], url: "/cantos/src/chtml/a/alacenadelcordero.html"},
    {id:212,title: "Abbá Padre ", subtitle: "Romanos 8,15-17", category: "Eleccion", moments: ["Laudes/Visperas", "Comunión", "Nuevo Testamento"], url: "/cantos/src/chtml/a/abbapadre.html"},
    {id:213,title: "Adónde te escondiste amado ", subtitle: "Cántico Espiritual de san Juan de la Cruz – “Canciones entre el alma y el esposo”", category: "Eleccion", moments: ["Pascua"], url: "/cantos/src/chtml/a/adondeteescondisteamado.html"},
    {id:214,title: "Como condenados a muerte ", subtitle: "1ª Corintios 4,9-13", category: "Eleccion", moments: ["Nuevo Testamento"], url: "/cantos/src/chtml/c/comocondenadosamuerte.html"},
    {id:215,title: "Como destila la miel ", subtitle: "Oda XL de Salomón", category: "Eleccion", moments: ["Pascua", "Comunión"], url: "/cantos/src/chtml/c/comodestilalamiel.html"},
    {id:216,title: "Como lirio entre los cardos ", subtitle: "Cantar de los Cantares 1,13ss", category: "Eleccion", moments: ["Pascua", "Comunión", "Antiguo Testamento"], url: "/cantos/src/chtml/c/comolirioentreloscardos.html"},
    {id:217,title: "Cuando dormía", subtitle: "Cantar de los Cantares 5,2ss", category: "Eleccion", moments: ["Pascua", "Laudes/Visperas", "Comunión", "Antiguo Testamento"], url: "/cantos/src/chtml/c/cuandodormia.html"},
    {id:218,title: "El Espíritu del Señor está sobre mí ", subtitle: "Lucas 4,18 – Isaías 61,1-3", category: "Eleccion", moments: ["Laudes/Visperas", "Final", "Antiguo Testamento", "Nuevo Testamento"], url: "/cantos/src/chtml/e/elespiritudelsenorestasobremi.html"},
    {id:219,title: "El jacal de los pastores", subtitle: "Cantar de los Cantares 1,2-8", category: "Eleccion", moments: ["Pascua", "Comunión", "Antiguo Testamento"], url: "/cantos/src/chtml/e/eljacaldelospastores.html"},
    {id:220,title: "En una noche oscura", subtitle: "Subida al Monte Carmelo – San Juan de la Cruz", category: "Eleccion", moments: ["Fracción del Pan"], url: "/cantos/src/chtml/e/enunanocheoscura.html"},
    {id:221,title: "Extiendo mis manos", subtitle: "Oda XXVII de Salomón", category: "Eleccion", moments: ["Cuaresma", "Fracción del Pan"], url: "/cantos/src/chtml/e/extiendomismanos.html"},
    {id:222,title: "Hermosa eres, amiga mía ", subtitle: "Cantar de los Cantares 6 y 7 – Quinto Poema", category: "Eleccion", moments: ["Pascua", "Comunión", "Antiguo Testamento"], url: "/cantos/src/chtml/h/hermosaeresamigamia.html"},
    {id:223,title: "Himno a la caridad ", subtitle: "1ª Corintios 13,1-13", category: "Eleccion", moments: ["Pentecostés", "Comunión", "Nuevo Testamento"], url: "/cantos/src/chtml/h/himnoalacaridad.html"},
    {id:224,title: "Huye, amado mío ", subtitle: "Cantar de los Cantares 8,10-14", category: "Eleccion", moments: ["Pascua", "Comunión", "Final", "Antiguo Testamento"], url: "/cantos/src/chtml/h/huyeamadomio.html"},
    {id:225,title: "Jesús recorría todas las ciudades", subtitle: "Mateo 9,35ss", category: "Eleccion", moments: ["Nuevo Testamento"], url: "/cantos/src/chtml/j/jesusrecorriatodaslasciudades.html"},
    {id:226,title: "La cordera de Dios", subtitle: "Mateo 1,18ss", category: "Eleccion", moments: ["Navidad", "Virgen", "Nuevo Testamento"], url: "/cantos/src/chtml/l/lacorderadedios.html"},
    {id:227,title: "La paloma voló", subtitle: "Oda XXIV de Salomón", category: "Eleccion", moments: ["Laudes/Visperas", "Comunión"], url: "/cantos/src/chtml/l/lapalomavolo.html"},
    {id:228,title: "La voz de mi amado", subtitle: "Cantar de los Cantares 2,8-17", category: "Eleccion", moments: ["Comunión", "Antiguo Testamento"], url: "/cantos/src/chtml/l/lavozdemiamado.html"},
    {id:229,title: "Me robaste el corazón ", subtitle: "Cantar de los Cantares 4,9-16.5,1", category: "Eleccion", moments: ["Pascua", "Comunión", "Antiguo Testamento"], url: "/cantos/src/chtml/m/merobasteelcorazon.html"},
    {id:230,title: "No resistáis al mal", subtitle: "Mateo 5,38ss", category: "Eleccion", moments: ["Comunión", "Nuevo Testamento"], url: "/cantos/src/chtml/n/noresistaisalmal.html"},
    {id:231,title: "Noli me tangere ", subtitle: "Juan 20,15-17", category: "Eleccion", moments: ["Pascua", "Nuevo Testamento"], url: "/cantos/src/chtml/n/nolimetangere.html"},
    {id:232,title: "Quién es ésta que sube del desierto", subtitle: "Cantar de los Cantares 8,5-7", category: "Eleccion", moments: ["Comunión", "Final", "Antiguo Testamento"], url: "/cantos/src/chtml/q/quienesestaquesubedeldesierto.html"},
    {id:233,title: "Quiero andar", subtitle: "Canto Sefardí", category: "Eleccion", moments: ["Final"], url: "/cantos/src/chtml/q/quieroandar.html"},
    {id:234,title: "Sermón de la montaña", subtitle: "Lucas 6,20-38", category: "Eleccion", moments: ["Comunión", "Nuevo Testamento"], url: "/cantos/src/chtml/s/sermondelamontana.html"},
    {id:235,title: "Suba el Esposo al leño de su tálamo", subtitle: "Himno de san Quodvultdeus", category: "Eleccion", moments: ["Pascua"], url: "/cantos/src/chtml/s/subaelesposoallenodesutalamo.html"},
    {id:236,title: "Tú eres mi esperanza, Señor", subtitle: "Oda XXIX de Salomón", category: "Eleccion", moments: ["Adviento", "Cuaresma"], url: "/cantos/src/chtml/t/tueresmiesperanzasenor.html"},
    {id:237,title: "Ven del Líbano", subtitle: "Cantar de los Cantares 4,8ss", category: "Eleccion", moments: ["Entrada", "Antiguo Testamento"], url: "/cantos/src/chtml/v/vendellibano.html"},
    {id:239,title: "Prountuario de Acordes", subtitle: "Notas", category: "Notas", moments: ["Notas"], url: "/cantos/src/chtml/p/prountuariodeacordes.html"}      

];